---
title: Nerdy Nuggies
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: posts-5
- scope:
    path: ''
    type: posts
  values:
    layout: posts-10
- scope:
    path: ''
    type: posts
  values:
    layout: posts-15
email: makalatrezise@gmail.com
description: 'A blog to of nerdy nuggets to fuel your brain. '
baseurl: ''
url: ''
theme: minima
plugins:
- jekyll-feed
assets:
  sources: "-_assets/fonts"
permalink: "/blog/:title"
section: true
netlifycms: true
analytics: false
sass:
  style: compressed
  sass_dir: _sass
compress_html:
  clippings: all
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- README.md
- LICENSE.txt
- netlify.toml
- feed.xml
- Gemfile
- Gemfile.lock
- docker-compose.yml
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
